export const rw06UmkmData: Array<{
  namaUsaha: string;
  deskripsi: string;
  alamat: string;
  namaPemilik: string;
  whatsapp: string;
  tanggalMulai: Date;
  showPhotoAlert: boolean;
  categorySlug: string;
  socialLinksCount: number;
  hasImages: boolean;
  isActive?: boolean;
}> = [
  {
    namaUsaha: "Warung Ramesan Bu Masripah & Sabila Catering",
    deskripsi: "Aneka masakan",
    alamat: "Jaten Gede Timur 3, RT 01/RW 06, Pedurungan Tengah, Semarang",
    namaPemilik: "Masripah",
    whatsapp: "085780057325",
    tanggalMulai: new Date("2025-01-01"),
    showPhotoAlert: true,
    categorySlug: "makanan-minuman",
    socialLinksCount: 0,
    hasImages: false,
    isActive: false,
  },
  {
    namaUsaha: "Tahu Bacem Bu Dewi",
    deskripsi: "Makanan (Tahu Bacem)",
    alamat: "Jaten Gede Timur 3, RT 01/RW 06, Pedurungan Tengah, Semarang",
    namaPemilik: "Dewi B",
    whatsapp: "081226887080",
    tanggalMulai: new Date("2025-01-01"),
    showPhotoAlert: true,
    categorySlug: "makanan-minuman",
    socialLinksCount: 0,
    hasImages: false,
    isActive: false,
  },
  {
    namaUsaha: "Anugerah",
    deskripsi: "Produksi Brownies, Cake, Bolu, Kue Kering",
    alamat: "Jl. Taman Tlogomulyo, RT 02/RW 06, Pedurungan Tengah, Semarang",
    namaPemilik: "Emy Septiyani",
    whatsapp: "085727149070",
    tanggalMulai: new Date("2025-01-01"),
    showPhotoAlert: true,
    categorySlug: "makanan-minuman",
    socialLinksCount: 0,
    hasImages: false,
    isActive: false,
  },
  {
    namaUsaha: "Warung Yambe Madura",
    deskripsi: "Pengolahan ayam dan bebek",
    alamat: "Jl. Taman Tlogomulyo Selatan IV, RT 02/RW 06, Pedurungan Tengah, Semarang",
    namaPemilik: "Hosliyeh",
    whatsapp: "087849341762",
    tanggalMulai: new Date("2025-01-01"),
    showPhotoAlert: true,
    categorySlug: "makanan-minuman",
    socialLinksCount: 0,
    hasImages: false,
    isActive: false,
  },
  {
    namaUsaha: "Sazardus",
    deskripsi: "Sempolan dan kerupuk seblak",
    alamat: "Jl. Taman Tlogomulyo, RT 02/RW 06, Pedurungan Tengah, Semarang",
    namaPemilik: "Yanti Variana Dewi",
    whatsapp: "083842559704",
    tanggalMulai: new Date("2025-01-01"),
    showPhotoAlert: true,
    categorySlug: "makanan-minuman",
    socialLinksCount: 0,
    hasImages: false,
    isActive: false,
  },
  {
    namaUsaha: "Jamu Bu Dwi",
    deskripsi: "Jamu",
    alamat: "Jl. Taman Tlogomulyo, RT 02/RW 06, Pedurungan Tengah, Semarang",
    namaPemilik: "Dwi Hidayani",
    whatsapp: "08812623488",
    tanggalMulai: new Date("2025-01-01"),
    showPhotoAlert: true,
    categorySlug: "makanan-minuman",
    socialLinksCount: 0,
    hasImages: false,
    isActive: false,
  },
  {
    namaUsaha: "Soto ayam dan mie kopyok Mas Lisin",
    deskripsi: "Soto ayam dan Mie kopyok",
    alamat: "Jl. Taman Tlogomulyo, RT 02/RW 06, Pedurungan Tengah, Semarang",
    namaPemilik: "Mukhlisin",
    whatsapp: "08995515424",
    tanggalMulai: new Date("2025-01-01"),
    showPhotoAlert: true,
    categorySlug: "makanan-minuman",
    socialLinksCount: 0,
    hasImages: false,
    isActive: false,
  },
  {
    namaUsaha: "Roti Basah Raswan",
    deskripsi: "Roti basah",
    alamat: "Jl. Taman Tlogomulyo Selatan, RT 04/RW 06, Pedurungan Tengah, Semarang",
    namaPemilik: "Raswan",
    whatsapp: "081548711586",
    tanggalMulai: new Date("2025-01-01"),
    showPhotoAlert: true,
    categorySlug: "makanan-minuman",
    socialLinksCount: 0,
    hasImages: false,
    isActive: false,
  },
  {
    namaUsaha: "Peyek Bu Indah",
    deskripsi: "Peyek",
    alamat: "Jl. Taman Tlogomulyo Selatan, RT 04/RW 06, Pedurungan Tengah, Semarang",
    namaPemilik: "Indahyati",
    whatsapp: "085324341286",
    tanggalMulai: new Date("2025-01-01"),
    showPhotoAlert: true,
    categorySlug: "makanan-minuman",
    socialLinksCount: 0,
    hasImages: false,
    isActive: false,
  },
  {
    namaUsaha: "Gorengan Pak No",
    deskripsi: "Gorengan",
    alamat: "Jl. Taman Tlogomulyo Selatan, RT 04/RW 06, Pedurungan Tengah, Semarang",
    namaPemilik: "Misno",
    whatsapp: "085606769930",
    tanggalMulai: new Date("2025-01-01"),
    showPhotoAlert: true,
    categorySlug: "makanan-minuman",
    socialLinksCount: 0,
    hasImages: false,
    isActive: false,
  },
  {
    namaUsaha: "Aneka Snack Parni",
    deskripsi: "Aneka Snack",
    alamat: "Jl. Taman Tlogomulyo Selatan, RT 04/RW 06, Pedurungan Tengah, Semarang",
    namaPemilik: "Parni",
    whatsapp: "081234567890",
    tanggalMulai: new Date("2025-01-01"),
    showPhotoAlert: true,
    categorySlug: "makanan-minuman",
    socialLinksCount: 0,
    hasImages: false,
    isActive: false,
  },
  {
    namaUsaha: "Bakmi Jowo Mas Sastro",
    deskripsi: "Bakmi Jowo",
    alamat: "Jl. Taman Tlogomulyo Selatan, RT 04/RW 06, Pedurungan Tengah, Semarang",
    namaPemilik: "Arifin",
    whatsapp: "082314884045",
    tanggalMulai: new Date("2025-01-01"),
    showPhotoAlert: true,
    categorySlug: "makanan-minuman",
    socialLinksCount: 0,
    hasImages: false,
    isActive: false,
  },
  {
    namaUsaha: "Penyetan Muhtarom",
    deskripsi: "Penyetan",
    alamat: "Jl. Taman Tlogomulyo Selatan, RT 04/RW 06, Pedurungan Tengah, Semarang",
    namaPemilik: "Muhtarom",
    whatsapp: "081234567890",
    tanggalMulai: new Date("2025-01-01"),
    showPhotoAlert: true,
    categorySlug: "makanan-minuman",
    socialLinksCount: 0,
    hasImages: false,
    isActive: false,
  },
  {
    namaUsaha: "Lien Cafe",
    deskripsi: "Siomay",
    alamat: "Perum Pedurungan Sari, RT 06/RW 06, Pedurungan Tengah, Semarang",
    namaPemilik: "Chusnul Chotimah",
    whatsapp: "082225133837",
    tanggalMulai: new Date("2025-01-01"),
    showPhotoAlert: true,
    categorySlug: "makanan-minuman",
    socialLinksCount: 0,
    hasImages: false,
    isActive: false,
  },
  {
    namaUsaha: "King Banana's",
    deskripsi: "Pempek dan Kue kering",
    alamat: "Perum Pedurungan Sari, RT 06/RW 06, Pedurungan Tengah, Semarang",
    namaPemilik: "Yuni Lestari",
    whatsapp: "085226016626",
    tanggalMulai: new Date("2025-01-01"),
    showPhotoAlert: true,
    categorySlug: "makanan-minuman",
    socialLinksCount: 0,
    hasImages: false,
    isActive: false,
  },
  {
    namaUsaha: "Ayesha Dessert & Cakes",
    deskripsi: "Cake dan Dessert",
    alamat: "Perum Pedurungan Sari, RT 06/RW 06, Pedurungan Tengah, Semarang",
    namaPemilik: "Sri Mulyati Herlina",
    whatsapp: "081327662627",
    tanggalMulai: new Date("2025-01-01"),
    showPhotoAlert: true,
    categorySlug: "makanan-minuman",
    socialLinksCount: 0,
    hasImages: false,
    isActive: false,
  },
  {
    namaUsaha: "Soto Rempah dan Ayam Goreng Maskur",
    deskripsi: "Soto rempah dan Ayam goreng",
    alamat: "Perum Pedurungan Sari, RT 06/RW 06, Pedurungan Tengah, Semarang",
    namaPemilik: "Ema Susilowati",
    whatsapp: "08881980476",
    tanggalMulai: new Date("2025-01-01"),
    showPhotoAlert: true,
    categorySlug: "makanan-minuman",
    socialLinksCount: 0,
    hasImages: false,
    isActive: false,
  },
  {
    namaUsaha: "Klapertart Dapur Monic",
    deskripsi: "Produksi kue dari kelapa",
    alamat: "Perum Telaga Kencana No. 35, RT 07/RW 06, Pedurungan Tengah, Semarang",
    namaPemilik: "Monika Febriani",
    whatsapp: "085641981223",
    tanggalMulai: new Date("2025-01-01"),
    showPhotoAlert: true,
    categorySlug: "makanan-minuman",
    socialLinksCount: 0,
    hasImages: false,
    isActive: false,
  },
  {
    namaUsaha: "Pempek Tungku Ni",
    deskripsi: "Produksi pempek",
    alamat: "Perum Telaga Kencana No. 38, RT 07/RW 06, Pedurungan Tengah, Semarang",
    namaPemilik: "Rani",
    whatsapp: "08122920356",
    tanggalMulai: new Date("2025-01-01"),
    showPhotoAlert: true,
    categorySlug: "makanan-minuman",
    socialLinksCount: 0,
    hasImages: false,
    isActive: false,
  },
  {
    namaUsaha: "Jiua.co",
    deskripsi: "Produksi puding coklat",
    alamat: "Perum Telaga Kencana No. 41, RT 07/RW 06, Pedurungan Tengah, Semarang",
    namaPemilik: "Dinar Hayu",
    whatsapp: "085876654775",
    tanggalMulai: new Date("2025-01-01"),
    showPhotoAlert: true,
    categorySlug: "makanan-minuman",
    socialLinksCount: 0,
    hasImages: false,
    isActive: false,
  },
  {
    namaUsaha: "Davie Cake and Cookies",
    deskripsi: "Produksi snack, Cake, Cookies, Puding, dan Minuman",
    alamat: "Perum Graha Sigi Permai Blok A.8, RT 09/RW 06, Pedurungan Tengah, Semarang",
    namaPemilik: "Via Yudistira Ekti Indarta",
    whatsapp: "087870104289",
    tanggalMulai: new Date("2025-01-01"),
    showPhotoAlert: true,
    categorySlug: "makanan-minuman",
    socialLinksCount: 0,
    hasImages: false,
    isActive: false,
  },
  {
    namaUsaha: "Mie Ayam Pangsit Sigi",
    deskripsi: "Produksi mie, Pangsit, Bakso, Minuman",
    alamat: "Perum Graha Sigi Permai Blok F.8, RT 09/RW 06, Pedurungan Tengah, Semarang",
    namaPemilik: "Lo Sun Mei (Cik Meme)",
    whatsapp: "081336129891",
    tanggalMulai: new Date("2025-01-01"),
    showPhotoAlert: true,
    categorySlug: "makanan-minuman",
    socialLinksCount: 0,
    hasImages: false,
    isActive: false,
  },
];

export const rw06ImageLinks: Array<{
  namaUsaha: string;
  images: Array<{ publicId: string; url: string; urutan: number }>;
}> = [
  {
    namaUsaha: "Warung Ramesan Bu Masripah & Sabila Catering",
    images: [
      { publicId: "umkm/warung-ramesan-masripah-1", url: "https://picsum.photos/seed/umkm-warung-ramesan-masripah-1/800/600", urutan: 0 },
      { publicId: "umkm/warung-ramesan-masripah-2", url: "https://picsum.photos/seed/umkm-warung-ramesan-masripah-2/800/600", urutan: 1 },
      { publicId: "umkm/warung-ramesan-masripah-3", url: "https://picsum.photos/seed/umkm-warung-ramesan-masripah-3/800/600", urutan: 2 },
    ],
  },
  {
    namaUsaha: "Tahu Bacem Bu Dewi",
    images: [
      { publicId: "umkm/tahu-bacem-bu-dewi-1", url: "https://picsum.photos/seed/umkm-tahu-bacem-bu-dewi-1/800/600", urutan: 0 },
      { publicId: "umkm/tahu-bacem-bu-dewi-2", url: "https://picsum.photos/seed/umkm-tahu-bacem-bu-dewi-2/800/600", urutan: 1 },
      { publicId: "umkm/tahu-bacem-bu-dewi-3", url: "https://picsum.photos/seed/umkm-tahu-bacem-bu-dewi-3/800/600", urutan: 2 },
    ],
  },
  {
    namaUsaha: "Anugerah",
    images: [
      { publicId: "umkm/anugerah-1", url: "https://picsum.photos/seed/umkm-anugerah-1/800/600", urutan: 0 },
      { publicId: "umkm/anugerah-2", url: "https://picsum.photos/seed/umkm-anugerah-2/800/600", urutan: 1 },
      { publicId: "umkm/anugerah-3", url: "https://picsum.photos/seed/umkm-anugerah-3/800/600", urutan: 2 },
    ],
  },
  {
    namaUsaha: "Warung Yambe Madura",
    images: [
      { publicId: "umkm/warung-yambe-madura-1", url: "https://picsum.photos/seed/umkm-warung-yambe-madura-1/800/600", urutan: 0 },
      { publicId: "umkm/warung-yambe-madura-2", url: "https://picsum.photos/seed/umkm-warung-yambe-madura-2/800/600", urutan: 1 },
      { publicId: "umkm/warung-yambe-madura-3", url: "https://picsum.photos/seed/umkm-warung-yambe-madura-3/800/600", urutan: 2 },
    ],
  },
  {
    namaUsaha: "Sazardus",
    images: [
      { publicId: "umkm/sazardus-1", url: "https://picsum.photos/seed/umkm-sazardus-1/800/600", urutan: 0 },
      { publicId: "umkm/sazardus-2", url: "https://picsum.photos/seed/umkm-sazardus-2/800/600", urutan: 1 },
      { publicId: "umkm/sazardus-3", url: "https://picsum.photos/seed/umkm-sazardus-3/800/600", urutan: 2 },
    ],
  },
  {
    namaUsaha: "Jamu Bu Dwi",
    images: [
      { publicId: "umkm/jamu-bu-dwi-1", url: "https://picsum.photos/seed/umkm-jamu-bu-dwi-1/800/600", urutan: 0 },
      { publicId: "umkm/jamu-bu-dwi-2", url: "https://picsum.photos/seed/umkm-jamu-bu-dwi-2/800/600", urutan: 1 },
      { publicId: "umkm/jamu-bu-dwi-3", url: "https://picsum.photos/seed/umkm-jamu-bu-dwi-3/800/600", urutan: 2 },
    ],
  },
  {
    namaUsaha: "Soto ayam dan mie kopyok Mas Lisin",
    images: [
      { publicId: "umkm/soto-mas-lisin-1", url: "https://picsum.photos/seed/umkm-soto-mas-lisin-1/800/600", urutan: 0 },
      { publicId: "umkm/soto-mas-lisin-2", url: "https://picsum.photos/seed/umkm-soto-mas-lisin-2/800/600", urutan: 1 },
      { publicId: "umkm/soto-mas-lisin-3", url: "https://picsum.photos/seed/umkm-soto-mas-lisin-3/800/600", urutan: 2 },
    ],
  },
  {
    namaUsaha: "Roti Basah Raswan",
    images: [
      { publicId: "umkm/roti-basah-raswan-1", url: "https://picsum.photos/seed/umkm-roti-basah-raswan-1/800/600", urutan: 0 },
      { publicId: "umkm/roti-basah-raswan-2", url: "https://picsum.photos/seed/umkm-roti-basah-raswan-2/800/600", urutan: 1 },
      { publicId: "umkm/roti-basah-raswan-3", url: "https://picsum.photos/seed/umkm-roti-basah-raswan-3/800/600", urutan: 2 },
    ],
  },
  {
    namaUsaha: "Peyek Bu Indah",
    images: [
      { publicId: "umkm/peyek-bu-indah-1", url: "https://picsum.photos/seed/umkm-peyek-bu-indah-1/800/600", urutan: 0 },
      { publicId: "umkm/peyek-bu-indah-2", url: "https://picsum.photos/seed/umkm-peyek-bu-indah-2/800/600", urutan: 1 },
      { publicId: "umkm/peyek-bu-indah-3", url: "https://picsum.photos/seed/umkm-peyek-bu-indah-3/800/600", urutan: 2 },
    ],
  },
  {
    namaUsaha: "Gorengan Pak No",
    images: [
      { publicId: "umkm/gorengan-pak-no-1", url: "https://picsum.photos/seed/umkm-gorengan-pak-no-1/800/600", urutan: 0 },
      { publicId: "umkm/gorengan-pak-no-2", url: "https://picsum.photos/seed/umkm-gorengan-pak-no-2/800/600", urutan: 1 },
      { publicId: "umkm/gorengan-pak-no-3", url: "https://picsum.photos/seed/umkm-gorengan-pak-no-3/800/600", urutan: 2 },
    ],
  },
  {
    namaUsaha: "Aneka Snack Parni",
    images: [
      { publicId: "umkm/aneka-snack-parni-1", url: "https://picsum.photos/seed/umkm-aneka-snack-parni-1/800/600", urutan: 0 },
      { publicId: "umkm/aneka-snack-parni-2", url: "https://picsum.photos/seed/umkm-aneka-snack-parni-2/800/600", urutan: 1 },
      { publicId: "umkm/aneka-snack-parni-3", url: "https://picsum.photos/seed/umkm-aneka-snack-parni-3/800/600", urutan: 2 },
    ],
  },
  {
    namaUsaha: "Bakmi Jowo Mas Sastro",
    images: [
      { publicId: "umkm/bakmi-jowo-mas-sastro-1", url: "https://picsum.photos/seed/umkm-bakmi-jowo-mas-sastro-1/800/600", urutan: 0 },
      { publicId: "umkm/bakmi-jowo-mas-sastro-2", url: "https://picsum.photos/seed/umkm-bakmi-jowo-mas-sastro-2/800/600", urutan: 1 },
      { publicId: "umkm/bakmi-jowo-mas-sastro-3", url: "https://picsum.photos/seed/umkm-bakmi-jowo-mas-sastro-3/800/600", urutan: 2 },
    ],
  },
  {
    namaUsaha: "Penyetan Muhtarom",
    images: [
      { publicId: "umkm/penyetan-muhtarom-1", url: "https://picsum.photos/seed/umkm-penyetan-muhtarom-1/800/600", urutan: 0 },
      { publicId: "umkm/penyetan-muhtarom-2", url: "https://picsum.photos/seed/umkm-penyetan-muhtarom-2/800/600", urutan: 1 },
      { publicId: "umkm/penyetan-muhtarom-3", url: "https://picsum.photos/seed/umkm-penyetan-muhtarom-3/800/600", urutan: 2 },
    ],
  },
  {
    namaUsaha: "Lien Cafe",
    images: [
      { publicId: "umkm/lien-cafe-1", url: "https://picsum.photos/seed/umkm-lien-cafe-1/800/600", urutan: 0 },
      { publicId: "umkm/lien-cafe-2", url: "https://picsum.photos/seed/umkm-lien-cafe-2/800/600", urutan: 1 },
      { publicId: "umkm/lien-cafe-3", url: "https://picsum.photos/seed/umkm-lien-cafe-3/800/600", urutan: 2 },
    ],
  },
  {
    namaUsaha: "King Banana's",
    images: [
      { publicId: "umkm/king-bananas-1", url: "https://picsum.photos/seed/umkm-king-bananas-1/800/600", urutan: 0 },
      { publicId: "umkm/king-bananas-2", url: "https://picsum.photos/seed/umkm-king-bananas-2/800/600", urutan: 1 },
      { publicId: "umkm/king-bananas-3", url: "https://picsum.photos/seed/umkm-king-bananas-3/800/600", urutan: 2 },
    ],
  },
  {
    namaUsaha: "Ayesha Dessert & Cakes",
    images: [
      { publicId: "umkm/ayesha-dessert-cakes-1", url: "https://picsum.photos/seed/umkm-ayesha-dessert-cakes-1/800/600", urutan: 0 },
      { publicId: "umkm/ayesha-dessert-cakes-2", url: "https://picsum.photos/seed/umkm-ayesha-dessert-cakes-2/800/600", urutan: 1 },
      { publicId: "umkm/ayesha-dessert-cakes-3", url: "https://picsum.photos/seed/umkm-ayesha-dessert-cakes-3/800/600", urutan: 2 },
    ],
  },
  {
    namaUsaha: "Soto Rempah dan Ayam Goreng Maskur",
    images: [
      { publicId: "umkm/soto-maskur-1", url: "https://picsum.photos/seed/umkm-soto-maskur-1/800/600", urutan: 0 },
      { publicId: "umkm/soto-maskur-2", url: "https://picsum.photos/seed/umkm-soto-maskur-2/800/600", urutan: 1 },
      { publicId: "umkm/soto-maskur-3", url: "https://picsum.photos/seed/umkm-soto-maskur-3/800/600", urutan: 2 },
    ],
  },
  {
    namaUsaha: "Klapertart Dapur Monic",
    images: [
      { publicId: "umkm/klapertart-dapur-monic-1", url: "https://picsum.photos/seed/umkm-klapertart-dapur-monic-1/800/600", urutan: 0 },
      { publicId: "umkm/klapertart-dapur-monic-2", url: "https://picsum.photos/seed/umkm-klapertart-dapur-monic-2/800/600", urutan: 1 },
      { publicId: "umkm/klapertart-dapur-monic-3", url: "https://picsum.photos/seed/umkm-klapertart-dapur-monic-3/800/600", urutan: 2 },
    ],
  },
  {
    namaUsaha: "Pempek Tungku Ni",
    images: [
      { publicId: "umkm/pempek-tungku-ni-1", url: "https://picsum.photos/seed/umkm-pempek-tungku-ni-1/800/600", urutan: 0 },
      { publicId: "umkm/pempek-tungku-ni-2", url: "https://picsum.photos/seed/umkm-pempek-tungku-ni-2/800/600", urutan: 1 },
      { publicId: "umkm/pempek-tungku-ni-3", url: "https://picsum.photos/seed/umkm-pempek-tungku-ni-3/800/600", urutan: 2 },
    ],
  },
  {
    namaUsaha: "Jiua.co",
    images: [
      { publicId: "umkm/jiua-co-1", url: "https://picsum.photos/seed/umkm-jiua-co-1/800/600", urutan: 0 },
      { publicId: "umkm/jiua-co-2", url: "https://picsum.photos/seed/umkm-jiua-co-2/800/600", urutan: 1 },
      { publicId: "umkm/jiua-co-3", url: "https://picsum.photos/seed/umkm-jiua-co-3/800/600", urutan: 2 },
    ],
  },
  {
    namaUsaha: "Davie Cake and Cookies",
    images: [
      { publicId: "umkm/davie-cake-cookies-1", url: "https://picsum.photos/seed/umkm-davie-cake-cookies-1/800/600", urutan: 0 },
      { publicId: "umkm/davie-cake-cookies-2", url: "https://picsum.photos/seed/umkm-davie-cake-cookies-2/800/600", urutan: 1 },
      { publicId: "umkm/davie-cake-cookies-3", url: "https://picsum.photos/seed/umkm-davie-cake-cookies-3/800/600", urutan: 2 },
    ],
  },
  {
    namaUsaha: "Mie Ayam Pangsit Sigi",
    images: [
      { publicId: "umkm/mie-ayam-pangsit-sigi-1", url: "https://picsum.photos/seed/umkm-mie-ayam-pangsit-sigi-1/800/600", urutan: 0 },
      { publicId: "umkm/mie-ayam-pangsit-sigi-2", url: "https://picsum.photos/seed/umkm-mie-ayam-pangsit-sigi-2/800/600", urutan: 1 },
      { publicId: "umkm/mie-ayam-pangsit-sigi-3", url: "https://picsum.photos/seed/umkm-mie-ayam-pangsit-sigi-3/800/600", urutan: 2 },
    ],
  },
];
